base_url = "https://4bcx.gitlab.io/no-style-please/"
title = "no style, please!"
description = "A (nearly) no-CSS, fast, minimalist Zola theme."

compile_sass = true
generate_feed = true

taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true

[extra]
author = "Ahmed Alaa"
logo = "images/logo.png"
header_nav = [
    { name = "home", url = "/" },
    { name = "tags", url = "/tags" },
    { name = "categories", url = "/categories" },
    { name = "about", url = "/about" },
]
footer_nav = [
    { name = "Github", url = "https://www.github.com" },
    { name = "Twitter", url = "https://www.twitter.com" },
    { name = "Linkedin", url = "https://www.linkedin.com" },
]
